[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "my math note"
authors = [{name = "William Ng", email = "William.Ng@email.com"}]
dynamic = ["version", "description"]
